name: Second Tomorrow
favicon: null
layout_spectrum: 0.3793314532376826
typography_spectrum: 0.30649990728124976
title: Second Tomorrow Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fd1b1b'
    - '#ad1212'
    - '#590909'
    - '#8c0f0f'
  brandStrength: 0.5616690909955651
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
